---
# file: group_vars/all.yml

user_groups:
  - wheel
  - chris

config_users:
  chris:
    append: yes
    comment: "Chris Collins"
    groups:
      - chris
      - wheel
    home: /home/chris
    shell: /bin/bash
    authorized_keys: https://github.com/clcollins.keys

# Everything Fedora 30 (so...everything)
ansible_python_interpreter: /usr/bin/python3

system_management_packages:
  - ansible
  - git
  - restic
  - tmux

# workaround for j2 templating error
# with ansible vars and '.'s
homedir: /home/chris
