---
  - name: Package Repos | Fedora DwarfFortress | for FUN!
    yum_repository:
      name: dwarffortress
      description: Dwarf Fortress for Fedora $releasever
      baseurl: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/$releasever/$basearch/
      gpgkey: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/df_gpg_key
      enabled: yes
    when: ansible_distribution == "Fedora"

  - name: Package Repos | RPMFusion | for mplayer, others
    yum_repository:
      name: rpmfusion-free
      description: RPM Fusion for Fedora $releasever - Free
      baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-25
      #gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: yes
    when: ansible_distribution == "Fedora"

  - name: Package Repos | RPMFusion Updates | for mplayer, others
    yum_repository:
      name: rpmfusion-free-updates
      description: RPM Fusion for Fedora $releasever - Free - Updates
      baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-25
      #gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: yes
    when: ansible_distribution == "Fedora"

