---
  - name: Package Repos | Use Duke Fedora Mirror
    yum_repository:
      name: duke-fedora
      description: Duke University Fedora Mirror
      priority: 10
      baseurl: https://archive.linux.duke.edu/fedora/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      gpgcheck: yes
      enabled: yes
    tags:
      - repos
      - duke-repos
      - duke-fedora-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | Use Duke Fedora Updates Mirror
    yum_repository:
      name: duke-fedora-updates
      description: Duke University Fedora Mirror
      priority: 10
      baseurl: https://archive.linux.duke.edu/fedora/pub/fedora/linux/updates/$releasever/Everything/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
      gpgcheck: yes
      enabled: yes
    tags:
      - repos
      - duke-repos
      - duke-fedora-updates-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | Use Duke EPEL Mirror
    yum_repository:
      name: duke-epel
      description: Duke University EPEL Mirror
      priority: 10
      baseurl: http://archive.linux.duke.edu/fedora/pub/epel/$releasever/$basearch/
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever
      gpgcheck: yes
      enabled: yes
    tags:
      - repos
      - duke-repos
      - duke-fedora-epel-repo
    when: ansible_distribution == "Fedora"
    become: true

# Apparently this is in the rpmfusion-nonfree repo, and this guy no longer packages
# STATE ABSENT
#  - name: Package Repos | Fedora DwarfFortress | for FUN!
#    yum_repository:
#      state: absent
#      name: dwarffortress
#      description: Dwarf Fortress for Fedora $releasever
#      baseurl: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/$releasever/$basearch/
#      gpgkey: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/df_gpg_key
#      enabled: yes
#    tags:
#      - repos
#    when: ansible_distribution == "Fedora"
#    become: true

  - name: Package Repos | RPMFusion | for mplayer, others
    yum_repository:
      name: rpmfusion-free
      description: RPM Fusion for Fedora $releasever - Free
      baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: yes
    tags:
      - repos
      - rpmfusion-repos
      - rpmfusion-free-repos
      - rpmfusion-free-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | RPMFusion Updates | for mplayer, others
    yum_repository:
      name: rpmfusion-free-updates
      description: RPM Fusion for Fedora $releasever - Free - Updates
      baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      #gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: no
    tags:
      - repos
      - rpmfusion-repos
      - rpmfusion-free-repos
      - rpmfusion-free-updates-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | RPMFusion Nonfree
    yum_repository:
      name: rpmfusion-nonfree
      description: RPM Fusion for Fedora $releasever - Nonfree
      metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
      enabled: 1
      metadata_expire: 14d
      gpgcheck: 1
      repo_gpgcheck: 0
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    tags:
      - repos
      - rpmfusion-repos
      - rpmfusion-nonfree-repos
      - rpmfusion-nonfree-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | RPMFusion Nonfree Updates
    yum_repository:
      name: rpmfusion-nonfree-updates
      description: RPM Fusion for Fedora $releasever - Nonfree - Updates
      metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
      enabled: 1
      gpgcheck: 1
      repo_gpgcheck: 0
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    tags:
      - repos
      - rpmfusion-repos
      - rpmfusion-nonfree-repos
      - rpmfusion-nonfree-updates-repo
    when: ansible_distribution == "Fedora"
    become: true

  - name: Package Repos | RPMFusion Nonfree Steam
    yum_repository:
      name: rpmfusion-nonfree-steam
      description: RPM Fusion for Fedora $releasever - Nonfree - Steam
      metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-steam-$releasever&arch=$basearch
      enabled: 0
      gpgcheck: 1
      repo_gpgcheck: 0
      gpgkey: file:///usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    tags:
      - repos
      - rpmfusion-repos
      - rpmfusion-nonfree-repos
      - rpmfusion-nonfree-updates-repo
    when: ansible_distribution == "Fedora"
    become: true
