---
  - name: install Dwarf Fortress packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ dwarffortress_packages }}"
    become: true
    tags:
      - packages
      - dwarffortress

  - name: DwarfFortress Config Files | DF init.txt
    copy:
      src: dwarffortress_init.txt
      dest: "{{ ansible_env.HOME }}/.dwarffortress/data/init/init.txt"
    tags:
      - packages
      - config_files
      - dwarffortress

  # From http://www.bay12forums.com/smf/index.php?topic=158914.0
  - name: DwarfFortress Config Files | DF tile
    copy:
      src: hack_square_64x64.png
      dest: "{{ ansible_env.HOME }}/.dwarffortress/data/art/hack_square_64x64.png"
    tags:
      - packages
      - config_files
      - dwarffortress

  # DF package creates an "art" dir in the art dir...wtf
  - name: DwarfFortress Config Files | DF tile
    copy:
      src: hack_square_64x64.png
      dest: "{{ ansible_env.HOME }}/.dwarffortress/data/art/art/hack_square_64x64.png"
    tags:
      - packages
      - config_files
      - dwarffortress
