# file: cloud/tasks/main.yml

- name: Make sudoers
  copy:
    src: 10-wheel-nopasswd
    dest: /etc/sudoers.d/10-wheel-nopasswd
    owner: root
    group: root
    mode: '0660'
  become: True

- name: Remove Legacy sudoers
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/sudoers.d/010_sudoers-nopasswd
    - /etc/sudoers.d/010-wheel-nopasswd
    - /etc/sudoers.d/91-wheel-nopasswd
  become: True

