---
  - name: Packages | For container development
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - skopeo
      - atomic
      - origin-clients

  - name: Packages | Development stuff | for development
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - '@Development tools'
      - gcc-c++
      - redhat-rpm-config

  - name: Packages | for lolcommits
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - mplayer
      - ffmpeg
      - ImageMagick
      - ImageMagick-devel

  - name: Gems | lolcommits | for fun
    gem:
      name: lolcommits
      state: present
    become: true
    become_user: "{{ user }}"

  - name: Packages | for ruby
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - ruby-devel
      - rubygems
      - openssl-devel
      - mariadb-devel
      - readline-devel
      - rubypick

  - name: Gems | rails | for ruby
    gem:
      name: rails
      state: present
    become: true
    become_user: "{{ user }}"

  - name: Unpackaged Software | rbenv | for ruby
    git:
      repo: git://github.com/sstephenson/rbenv.git
      version: v1.1.0
      dest: "{{ homedir }}/.rbenv"
      update: no
      accept_hostkey: yes
    become: true
    become_user: "{{ user }}"

  - name: Unpackaged Software | ruby-build | for ruby
    git:
      repo: git://github.com/sstephenson/ruby-build.git
      version: v20170405
      dest: "{{ homedir }}/.rbenv/plugins/ruby-build"
      update: no
      accept_hostkey: yes
    become: true
    become_user: "{{ user }}"

  - name: Packages | container deps | for Buildah/containers
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - make
      - golang
      - bats
      - btrfs-progs-devel
      - device-mapper-devel
      - gpgme-devel
      - libassuan-devel
      - git
      - bzip2
      - golang-github-cpuguy83-go-md2man
