---
  - name: Packages | 'Development tools' group
    dnf:
      name: '@Development tools'
      state: present

  - name: Packages | redhat-rpm-config | for lolcommits
    dnf:
      name: redhat-rpm-config
      state: present

  - name: Packages | mplayer | for lolcommits
    dnf:
      name: mplayer
      state: present

  - name: Packages | ffmpeg | for lolcommits
    dnf:
      name: ffmpeg
      state: present

  - name: Packages | ImageMagick | for lolcommits
    dnf:
      name: ImageMagick
      state: present

  - name: Packages | ImageMagick-devel | for lolcommits
    dnf:
      name: ImageMagick-devel
      state: present

  - name: Gems | lolcommits | for fun
    gem:
      name: lolcommits
      state: present
    become: true
    become_user: "{{ user }}"

  - name: Packages | ruby-devel | for ruby
    dnf:
      name: ruby-devel
      state: present

  - name: Packages | rubygems | for ruby
    dnf:
      name: rubygems
      state: present

  - name: Packages | openssl-devel | for ruby
    dnf:
      name: openssl-devel
      state: present

  - name: Packages | mariadb-devel | for ruby
    dnf:
      name: mariadb-devel
      state: present

  - name: Packages | readline-devel | for ruby
    dnf:
      name: readline-devel
      state: present

  - name: Packages | rubypick | for ruby
    dnf:
      name: rubypick
      state: present

  - name: Gems | rails | for ruby
    gem:
      name: rails
      state: present
    become: true
    become_user: "{{ user }}"

  - name: Unpackaged Software | rbenv | for ruby
    git:
      repo: git://github.com/sstephenson/rbenv.git
      version: v1.1.0
      dest: "{{ homedir }}/.rbenv"
      update: no
    become: true
    become_user: "{{ user }}"

  - name: Unpackaged Software | ruby-build | for ruby
    git:
      repo: git://github.com/sstephenson/ruby-build.git
      version: v20170405
      dest: "{{ homedir }}/.rbenv/plugins/ruby-build"
      update: no
    become: true
    become_user: "{{ user }}"

