---
  - name: Packages | for Docker
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - docker
      - docker-compose
      - python3-docker-py
      - python3-dockerfile-parse
      - python3-docker-squash
      - python3-dockerpty

  - name: Config Files | Docker Sysconfig
    copy:
      src: docker_sysconfig
      dest: /etc/sysconfig/docker
    notify: reload docker

  - name: Config Files | Docker Storage Setup
    copy:
      src: docker-storage-setup
      dest: /etc/sysconfig/docker-storage-setup
    notify: reload docker

  - name: Config Files | Docker Network Setup
    copy:
      src: docker-network
      dest: /etc/sysconfig/docker-network
    notify: reload docker

  - name: Config Files | .docker Directory
    file:
      path: "{{ homedir }}/.docker"
      state: directory
      mode: 0755
      owner: "{{ user }}"
      group: "{{ user }}"

