---
  - include: repos.yml
  - include: docker.yml
  - include: development.yml
  - include: sshd.yml

  - name: Basic Packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - ansible
      - tmux
      - the_silver_searcher
      - vim-enhanced
      - pidgin
      - pidgin-otr
      - conky

  - name: Pip Packages | ansible-lint | validate Ansible role syntax
    pip:
      name: ansible-lint
      executable: pip2
      state: present
