# file: roles/flatpak/vars/main.yml

flatpak_remote_repositories:
  - name: flathub
    url:  "https://dl.flathub.org/repo/flathub.flatpakrepo"
  - name: fedora
    url: "oci+https://registry.fedoraproject.org"
    notes_for_chris: "Default Fedora flatpak repo"

flatpak_apps:
  - name:   com.discordapp.Discord
    state:  present
    method: user
    remote: flathub
  - name:   com.slack.Slack
    state:  present
    method: user
    remote: flathub
  - name:   org.gimp.GIMP
    state:  present
    method: user
    remote: flathub
  - name:   org.gnome.Podcasts
    state:  present
    method: user
    remote: flathub
  - name:   org.videolan.VLC
    state:  present
    method: user
    remote: flathub
