---
# file: roles/operator-sdk/tasks/main.yml

#- name: install operator-sdk dependencies
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - "{{ operator_sdk_package_dependencies }}"
#  become: true
#  tags:
#    - operator_sdk

- name: download Operator-SDK release
  get_url:
    url: "https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_release_version }}/operator-sdk-{{ operator_sdk_release_version }}-x86_64-linux-gnu"
    dest: "/tmp/operator-sdk-{{ operator_sdk_release_version }}-x86_64-linux-gnu"
    mode: '0755'
  register: sdk_download
  tags:
    - operator_sdk

- name: download Operator-SDK asc file
  get_url:
    url: "https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_release_version }}/operator-sdk-{{ operator_sdk_release_version }}-x86_64-linux-gnu.asc"
    dest: "/tmp/operator-sdk-{{ operator_sdk_release_version }}-x86_64-linux-gnu.asc"
  when: sdk_download is changed
  tags:
    - operator_sdk

- name: verify the downloaded binary
  command: 
    argv:
      - gpg
      - --verify
      - "operator-sdk-{{ operator_sdk_release_version }}-x86_64-linux-gnu.asc"
  args:
    chdir: /tmp/
  when: sdk_download is changed
  tags:
    - operator_sdk
