---
  - name: install conky packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ conky_packages }}"
    become: True
    tags:
      - conky

  - name: setup conky config directory
    file:
      path: "{{ ansible_env['HOME'] }}/.config/conky"
      state: directory
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"
      mode: 0775
    tags:
      - conky

  - name: copy conky dotfiles
    file:
      src: "{{ ansible_env['HOME'] }}/.config/conky"
      dest: "{{ ansible_env['HOME'] }}/.conky"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"
      state: link
    tags:
      - conky

  - name: copy conky config file
    copy:
      src: conky.conf
      dest: "{{ ansible_env['HOME'] }}/.config/conky/conky.conf"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"
    tags:
      - conky

  - name: clone Conky Revisited 2 repo
    git:
      repo: "https://github.com/xexpanderx/Conky-themes.git"
      dest: "{{ ansible_env['HOME'] }}/Projects/Conky-themes"
      version: master
      depth: 1
    tags:
      - conky

  # Gotta make this dumb symlink because the above keeps a subdir
  # in the repo
  - name : fix for Coky Revisited 2 subdir symlink
    file:
      src: "{{ ansible_env['HOME'] }}/Projects/Conky-themes/Conky-Revisited-2/Conky_Revisited_2/"
      dest: "{{ ansible_env['HOME'] }}/.config/conky/Conky_Revisited_2"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"
      state: link
    tags:
      - conky

  - name: install conky systemd unit file
    template:
      src: conky.service.j2
      dest: "{{ ansible_env['HOME'] }}/.config/systemd/user/conky.service"
      owner: "{{ ansible_env['USER'] }}"
      group: "{{ ansible_env['USER'] }}"
    register: conky_systemd_unit_file
    tags:
      - conky

  - name: reload systemd if unit file changed
    systemd:
      daemon-reload: true
      scope: user
    when: conky_systemd_unit_file is changed
    tags:
      - conky

  - name:  restart conky servicea if unit file changed
    systemd:
      name: conky.service
      scope: user
      no_block: yes
      enabled: yes
      state: restarted
    when: conky_systemd_unit_file is changed
    tags:
      - conky

  - name:  enable conky service
    systemd:
      name: conky.service
      scope: user
      no_block: yes
      enabled: yes
      state: started
    tags:
      - conky

