---
# file: roles/flatpak/tasks/main.yml

- name: Include Flatpak repositories
  ansible.builtin.include_tasks: repositories.yml
  when: flatpak_repositories_enable | bool
  tags: flatpak

- name: Include Flatpak packages
  ansible.builtin.include_tasks: packages.yml
  when: flatpak_packages_enable | bool
  tags: flatpak
