---
# file: roles/flatpak/tasks/main.yml

- name: Include Flatpak repositories
  ansible.builtin.include: repositories.yml
  when: flatpak_repositories_enable | bool

- name: Include Flatpak packages
  ansible.builtin.include: packages.yml
  when: flatpak_packages_enable | bool
