" Pathogen load
filetype off

call pathogen#infect()
call pathogen#helptags()

syntax on

filetype plugin indent on

autocmd Filetype yaml setlocal ts=2 sw=2 expandtab
autocmd FileType shell setlocal sw=2 sts=2 expandtab
autocmd Filetype python setlocal smarttab expandtab tabstop=4

set pastetoggle=<F2>

set ts=2
set sw=2
set softtabstop=2
set shiftwidth=2
