# file: roles/local_dns/tasks/main.yml
---
- name: Copy local DNS entries
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
    owner: root
    group: root
    mode: 0644
  notify: restart_dns
  become: True

