---
# file: roles/flatpak/default/main.yml

flatpak_repositories_enable: true
flatpak_packages_enable: true

flatpak_remote_repositories:
  flathub: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  fedora: "oci+https://registry.fedoraproject.org"

flatpak_packages:
  - name: com.discordapp.Discord
  - name: dev.vencord.Vesktop 
    remote: flathub
  - name: com.slack.Slack
    remote: flathub
  - name: social.whalebird.WhalebirdDesktop
    remote: flathub
  - name: org.gimp.GIMP
    remote: flathub

flatpak_packages_system:
  - name: org.freedesktop.Platform.ffmpeg-full//24.08
    remote: flathub
  - name: org.mozilla.firefox
    remote: flathub
  - name: org.vim.Vim
    remote: flathub

flatpak_rpms_redundant:
  - google-chrome
  - firefox

flatpak_flatpaks_redundant:
  - org.freedesktop.Platform.ffmpeg-full//21.08
  - org.freedesktop.Platform.ffmpeg-full//23.08
  - com.discordapp.Discord
