---
  - name: Run security checks
    include_role:
      name: common
      tasks_from: checks
    tags: checks

  - name: Install patching cron
    template:
      src: patchmonkey-daily.cron.j2
      dest: /etc/cron.daily/patchmonkey-daily.cron
      owner: root
      group: root
      mode: 0755
    become: true

  - name: Basic | Install Packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ basic_packages }}"
    become: true
    tags:
      - packages

  - name: Basic | Install Pidgin Packages
    package:
      name: "{{ item }}"
      state: present
    when: not skip_pidgin
    with_items: "{{ pidgin_packages }}"
    become: true
    tags:
      - packages

  - name: Vim | Install
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ vim_packages }}"
    become: true
    tags:
      - packages
      - vim

  - name: Vim Config | Copy .vimrc
    copy:
      src: vimrc
      dest: "{{ homedir }}/.vimrc"
    tags:
      - config_files
      - vim

  - name: Vim Config | Pathogen prep
    file:
      path: "{{ homedir }}/.vim/autoload"
      state: directory
      mode: 0755
    tags:
      - vim
      - vim_plugins

  - name: Vim Config | Pathogen prep
    file:
      path: "{{ homedir }}/.vim/bundle"
      state: directory
      mode: 0755
    tags:
      - vim
      - vim_plugins

  - name: Vim Config | Pathogen
    get_url:
      url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest: "{{ homedir }}/.vim/autoload/pathogen.vim"
      checksum: sha256:72a3f5db89ab36a207ea1a613a2afacd072ffd0f75da63fb74f0010f841d44b3 
    tags:
      - config_files
      - vim
      - vim_plugins

  - name: Vim Plugins | Dockerfile Vim
    git:
      repo: 'https://github.com/ekalinin/Dockerfile.vim.git'
      version: master
      dest: "{{ homedir }}/.vim/bundle/Dockerfile"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Vim Puppet
    git:
      repo: 'https://github.com/rodjek/vim-puppet.git'
      version: master
      dest: "{{ homedir }}/.vim/bundle/vim-puppet"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Syntastic
    git:
      repo: 'https://github.com/scrooloose/syntastic.git'
      version: 3.8.0
      dest: "{{ homedir }}/.vim/bundle/syntastic"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Tabular
    git:
      repo: 'https://github.com/godlygeek/tabular.git'
      version: 1.0.0
      dest: "{{ homedir }}/.vim/bundle/tabular"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Vim Go
    git:
      repo: 'https://github.com/fatih/vim-go'
      version: v1.12
      dest: "{{ homedir }}/.vim/bundle/vim-go"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Vim Markdown
    git:
      repo: 'https://github.com/plasticboy/vim-markdown.git'
      #version: 2.0.0
      version: HEAD
      dest: "{{ homedir }}/.vim/bundle/vim-markdown"
      accept_hostkey: yes
    tags:
      - skip_ansible_lint
      - vim
      - vim_plugins

  - name: Vim Plugins | Ansible Vim
    git:
      repo: 'https://github.com/pearofducks/ansible-vim.git'
      version: 1.0
      dest: "{{ homedir }}/.vim/bundle/ansible-vim"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins

  - name: Vim Plugins | Python-Flake8
    git:
      repo: 'https://github.com/nvie/vim-flake8.git'
      version: 1.6
      dest: "{{ homedir }}/.vim/bundle/vim-flake8"
      accept_hostkey: yes
    tags:
      - vim
      - vim_plugins
