# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export GOPATH=$HOME/.go
export GOBIN=$HOME/.local/bin
PATH=$PATH:$HOME/.local/bin:$HOME/bin:$GOPATH/bin
