---
# file: roles/work/tasks/yubikey_tools.yml
#
# Tools for setting-up/managing a Yubikey

- name: install packages for Yubikey seed/config
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yubikey_tools_packages }}"
  become: true
  tags:
    - yubikey
    - packages
