---
# file: roles/develop/tasks/glide.yml

- name: download Glide release
  get_url:
    url: "https://github.com/Masterminds/glide/releases/download/{{ glide_release_version }}/glide-{{ glide_release_version }}-linux-amd64.tar.gz"
    dest: "{{ glide_tarball }}"
  tags:
    - glide

- name: extract Glide
  unarchive:
    src: "{{ glide_tarball }}"
    dest: "{{ homedir }}/.local/bin"
    mode: '0755'
    extra_opts:
      - "linux-amd64/glide"
      - --strip-components=1
  tags:
    - glide
