---
# file: roles/develop/tasks/main.yml

# SELinux/python-selinux error for some reason
# - include_vars: glide.yml
# - import_tasks: glide.yml

- import_tasks: atom.yml

- import_tasks: vscode.yml

- name: install gvm dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ gvm_package_dependencies }}"
  become: true
  tags:
    - golang
    - gvm

# install build deps?  configure, make, etc?

# make ~/Projects
# clone standard projects
