---
# file: roles/develop/tasks/main.yml

# SELinux/python-selinux error for some reason
# - include_vars: glide.yml
# - import_tasks: glide.yml

- import_tasks: atom.yml

- import_tasks: vscode.yml

# install build deps?  configure, make, etc?

# make ~/Projects
# clone standard projects
