---
# file: roles/develop/tasks/main.yml

# SELinux/python-selinux error for some reason
# - include_vars: glide.yml
# - import_tasks: glide.yml

- import_tasks: atom.yml

- import_tasks: vscode.yml

- name: install Pomodoro timer extension
  package:
    name: "{{ pomodoro_package }}"
    state: present
  become: true
  tags:
    - packages

# install build deps?  configure, make, etc?

# make ~/Projects
# clone standard projects
