---
  - name: reload docker
    systemd:
      name: docker
      state: reloaded
    become: true

  - name: reload lvm2-lvmetad
    systemd:
      name: lvm2-lvmetad
      state: reloaded
    become: true

  - name: reload systemd-journald
    systemd:
      name: systemd-journald
      state: reloaded
    become: true

  - name: reload sshd
    systemd:
      name: sshd
      state: reloaded
    become: true

  - name: reload firewalld
    systemd:
      name: firewalld
      state: reloaded
    become: true
