---
  - name: restart docker
    service:
      name: docker
      state: restarted

  - name: restart lvm2-lvmetad
    service:
      name: lvm2-lvmetad
      state: restarted

  - name: restart systemd-journald
    service:
      name: systemd-journald
      state: restarted
