---
# file: roles/config/tasks/editor.yml

- debug:
    msg: "{{ ansible_facts }}"
  tags: config.editor

- name: Remove nano as default editor
  ansible.builtin.package:
    name: nano-default-editor
    state: absent
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  tags: config.editor

- name: Add vim as default editor
  ansible.builtin.package:
    name: vim-default-editor
    state: present
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  tags: config.editor
