---
# file: roles/config/tasks/editor.yml

- name: "config: Set VIM as default editor"
  ansible.builtin.alternatives:
    name: editor
    link: "{{ config_editor_link }}"
    path: "{{ config_editor_path }}"
  become: yes
  tags:
    - config_editor
