---
# file: roles/config/tasks/git.yml

- name: "git: Setup git"
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "{{ item.scope }}"
  loop: "{{ config_git_config }}"
  tags:
    - git_config
