---
# file: roles/config/tasks/gnome.yml

- name: "Set gnome theme"
  community.general.dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "{{ config_gnome_gtk_theme }}"
  tags:
    - config.gnome

