---
# file: roles/config/tasks/gnome.yml

- name: "config: Set dark theme"
  community.general.dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "{{ config_gnome_gtk_theme }}"
  tags:
    - config_gnome

- name: "config: retrieve default gnome-terminal profile UUID"
  community.general.dconf:
    key: /org/gnome/terminal/legacy/list[0]
    state: read
  register: gnome_terminal_default_uuid
  tags:
    - config_gnome

- name: debug
  debug:
    msg: "{{ gnome_terminal_config }}"
  tags:
    - config_gnome

- name: "config: set gnome-terminal settings"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ query('dict', gnome_terminal_config) }}"
  tags:
    - config_gnome
