---
# file: roles/config/tasks/localbin.yml

# This will copy files from bashrc.d to ~/.local/bin
# but will not overwrite any that are not Ansible-managed
- name: "shell: Setup ~/.local/bin directory"
  ansible.builtin.copy:
    src: bin/
    dest: "{{ item.value }}/.local/bin/"
    mode: 0755
  loop: "{{ user_homedirs | dict2items }}"
  tags:
    - config.localbin
  when: user_homedirs is defined
  become_user: "{{ item.key }}"
