---
# file: roles/config/tasks/networking.yml

- name: "config: Set hostname"
  ansible.builtin.hostname:
    name: "{{ config_hostname }}"
    use: systemd
  become: yes

- name: "config: Copy VPN CA"
  ansible.builtin.copy:
    src:   config_vpn_ca.pem
    dest:  "/etc/pki/tls/certs/{{ config_vpn_ca_file }}"
    owner: root
    group: root
    mode:  '0640'
  tags: vpn
  when: config_vpn_enable | bool
  become: yes
  notify: Restart NetworkManager
  
- name: "config: Copy VPN nmconnection files"
  ansible.builtin.template:
    src: ovpn.nmconnection.j2
    dest: "/etc/NetworkManager/system-connections/{{ item.key }}.nmconnection"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ query('dict', config_vpn_connections) }}"
  tags: vpn
  when: config_vpn_enable | bool
  become: yes
  notify: Restart NetworkManager
