---
# file: roles/config/tasks/shell.yml

# This will copy files from bashrc.d to ~/.bashrc.d
# but will not overwrite any that are not Ansible-managed
- name: "shell: Setup bashrc.d directory"
  ansible.builtin.copy:
    src: bashrc.d/
    dest: "{{ item.value }}/.bashrc.d/"
    mode: 0755
  loop: "{{ user_homedirs | dict2items }}"
  tags:
    - config.shell
  when: user_homedir is defined
  become_user: "{{ item.key }}"
