---
# file: roles/config/tasks/ssh.yml

- name: "ssh: Copy authorized_keys"
  authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value.authorized_keys }}"
    manage_dir: yes
  loop: "{{ query('dict', config_users) }}"
  tags:
    - ssh
  become: yes

- name: "ssh: SSH include dir"
  ansible.builtin.file:
    path: "{{ homedir }}/.ssh/ssh.d"
    state: directory
    mode: "0700"
  tags:
    - ssh

- name: "ssh: SSH config"
  ansible.builtin.copy:
    dest: "{{ homedir }}/.ssh/config"
    content: |
      # This file is managed by Ansible
      Include ~/.ssh/ssh.d/*
  tags:
    - ssh

- name: "ssh: ForwardAgent config"
  ansible.builtin.copy:
    dest: "{{ homedir }}/.ssh/ssh.d/10-forward_agent.conf"
    content: |
      # This file is managed by Ansible
      Host 192.168.1.*
        ForwardAgent yes
  tags:
    - ssh

- name: "ssh: allow agent forwarding"
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/10-allow_agent_forwarding.conf
    content: |
      # This file is managed by Ansible
      AllowAgentForwarding yes
  become: yes
  tags:
    - ssh


