---
#file: roles/config/tasks/users.yml

- name: "config: Merge variables"
  set_fact:
    config_users: "{{ config_users | combine(config_users_overrides, recursive=True) }}"
  when:
    - config_users_overrides | default()

- name: "config: Ensure groups exist"
  ansible.builtin.group:
    name: "{{ item.1 }}"
  loop: "{{ config_users|subelements('groups') }}"
  tags:
    - config.group
  become: yes

- name: "config: Ensure users exist"
  ansible.builtin.user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment }}"
    group: "{{ item.value.groups[0] }}"
    groups: "{{ item.value.groups[1:] }}"
    append: "{{ item.value.append }}"
    shell: "{{ item.value.shell }}"
  loop: "{{ query('dict', config_users) }}"
  tags:
    - config.user
  become: yes
