# file: roles/pi/tasks/main.yml
---
- name: Download rpidentify.sh
  get_url:
    url: "{{ rpidentify.url }}"
    dest: /usr/local/sbin/rpidentify
    checksum: "{{ rpidentify.sum }}"
    mode: '0555'
  tags:
    - pi
    - rpidentify
  become: True

- name: Remove legacy rpidentifies
  file:
    path: "{{ item }}"
    state: absent
  tags:
    - pi
    - rpidentify
  with_items:
    - /home/chris/rpidentify.sh
    - /usr/bin/rpidentify.sh
    - /usr/bin/rpidentify
  become: True
