---
  - name: Ensure firewalld installed
    package:
      name: "{{ firewalld }}"
      state: present
    become: true
    tags:
      - firewalld
      - packages

  - name: Install firewalld ansible dependencies
    package:
      name: "{{ item }}"
      state: present
    become: true
    with_items: "{{ firewalld_ansible_packages }}"
    tags:
      - firewalld
      - packages

  - name: Enable firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
    become: true
    tags:
      - firewalld

  - name: Set internal zones
    firewalld:
      source: "{{ item }}"
      zone: internal
      state: enabled
    with_items: "{{ internal_networks }}"
    become: true
    notify: reload firewalld
    tags:
      - firewalld
