---
  - name: Common | firewalld | Ensure Installed and Enabled
    systemd:
      name: firewalld
      enabled: yes
      state: started
    become: true
    notify: reload firewalld

  - name: Common | firewalld | Internal Zone Sources
    firewalld:
      source: "{{ item }}"
      zone: internal
      state: enabled
    with_items: "{{ internal_networks }}"
    become: true
    notify: reload firewalld

  - name: Common | firewalld | Fix "Cockpit" in FedoraServer zone
    lineinfile:
      path: /usr/lib/firewalld/zones/FedoraServer.xml
      regexp: '\s\s<service name="cockpit"/>'
      state: absent
    become: true
    notify: reload firewalld
