---
  - name: Common | Firewalld | Internal Zone Sources
    firewalld:
      source: "{{ item }}"
      zone: internal
      state: enabled
    with_items: "{{ internal_networks }}"
    become: true


