---
# file: common/tasks/main.yml

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - administration

- name: Copy authorized_keys
  authorized_key:
    user: "{{ ansible_env['USER'] }}"
    state: present
    key: https://github.com/clcollins.keys
  tags:
    - ssh

- name: install management packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_management_packages }}"
  become: true
  tags:
    - packages

- name: enable Systemd user dir
  file:
    path: /home/chris/.config/systemd/user
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: '0755'
    state: directory
  tags:
    - systemd

