---
# file: common/tasks/main.yml

- name: Create .bashrc
  copy:
    src: bashrc
    dest: "{{ homedir }}/.bashrc"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles
    - bash

- name: Create .bash_profile
  copy:
    src: bash_profile
    dest: "{{ homedir }}/.bash_profile"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles
    - bash

- name: Create .toprc
  copy:
    src: toprc
    dest: "{{ homedir }}/.toprc"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles`
    - top

- name: Create .tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ homedir }}/.tmux.conf"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles`
    - tmux

- name: Copy local binfiles
  copy:
    src: bin/
    dest: "{{ homedir }}/.local/bin/"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: '0755'
  tags:
    - userConfig
    - binFiles

- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ system_management_packages }}"
    - "{{ helpful_packages }}"
    - "{{ font_packages }}"
  become: true
  tags:
    - packages

- name: enable Systemd user dir
  file:
    path: /home/chris/.config/systemd/user
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: '0755'
    state: directory
  tags:
    - userConfig
    - dotFiles
    - systemd

- name: copy .vimrc file
  copy:
    src: vimrc
    dest: "{{ homedir }}/.vimrc"
  tags:
    - userConfig
    - dotFiles
    - vim 

- name: Vim config  | create Pathogen dirs
  file:
    path: "{{ homedir }}/.vim/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - bundle
    - autoload
  tags:
    - userConfig
    - vim

- name: Vim config | install Pathogen
  get_url:
    url: "{{ pathogen_vim.url }}"
    dest: "{{ homedir }}/.vim/autoload/{{ pathogen_vim.dest }}"
    checksum: "{{ pathogen_vim.checksum }}"
  tags:
    - userConfig
    - vim

- name: Install Vim plugins
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    dest: "{{ homedir }}/.vim/bundle/{{ item.dest }}"
    accept_hostkey: yes
    depth: 1
  with_items: "{{ vim_plugins }}"
  tags:
    - userConfig
    - vim
    
- name: Add completion scripts
  copy:
    src: "{{ item }}"
    dest: "/etc/bash_completion.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - hub_completion
  become: true
  tags:
    - completion

