---
  - name: Gather OS info
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
      - default.yml
    tags:
      - always

  - name: Set host nodename
    hostname:
      name: "{{ ansible_nodename }}"
    become: true

  # This isn't really "common" - reevaluate
  #- name: Common | Groups | "{{ user_groups }}"
  #  group:
  #    name: "{{ item }}"
  #    state: present
  #  with_items: "{{ user_groups }}"
  #  become: true

  - name: Add user "{{ user }}"
    user:
      name: "{{ user }}"
      group: "{{ user }}"
      shell: /bin/bash
    become: true

  - name: Create systemd userdir
    file:
      path: "{{ homedir }}/.config/systemd/user"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    when: ansible_service_mgr == "systemd"

  - name: Create .bashrc
    copy:
      src: bashrc
      dest: "{{ homedir }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Create .bash_profile
    copy:
      src: bash_profile
      dest: "{{ homedir }}/.bash_profile"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Create .toprc
    copy:
      src: toprc
      dest: "{{ homedir }}/.toprc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Create .giconfig
    template:
      src: git_config.j2
      dest: "{{ homedir }}/.gitconfig"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Enable git commit signing
    git_config:
      name: commit.gpgsign
      repo: "{{ homedir }}/.ansible"
      scope: global
      value: true

  - name: Copy authorized keys
    authorized_key:
      user: "{{ user }}"
      key: "{{ auth_key_url }}"

  - name: Install user binfiles
    copy:
      src: bin/
      dest: "{{ homedir }}/.local/bin/"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
