---
# file: common/tasks/main.yml

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - administration

- name: Copy authorized_keys
  authorized_key:
    user: "{{ ansible_env['USER'] }}"
    state: present
    key: https://github.com/clcollins.keys
  tags:
    - ssh

- name: Create .bashrc
  copy:
    src: bashrc
    dest: "{{ homedir }}/.bashrc"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles

- name: Create .bash_profile
  copy:
    src: bash_profile
    dest: "{{ homedir }}/.bash_profile"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles

- name: Create .toprc
  copy:
    src: toprc
    dest: "{{ homedir }}/.toprc"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: 0644
  tags:
    - userConfig
    - dotFiles`

- name: Copy local binfiles
  copy:
    src: bin/
    dest: "{{ homedir }}/.local/bin/"
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: '0755'
  tags:
    - userConfig
    - binFiles

- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ system_management_packages }}"
    - "{{ helpful_packages }}"
  become: true
  tags:
    - packages

- name: enable Systemd user dir
  file:
    path: /home/chris/.config/systemd/user
    owner: "{{ ansible_env['USER'] }}"
    group: "{{ ansible_env['USER'] }}"
    mode: '0755'
    state: directory
  tags:
    - systemd

