---
  - name: Common | Gather | Gather vars 
    include_role:
      name: common
      tasks_from: gather

  - name: Common | Admin | hostname
    hostname:
      name: "{{ ansible_nodename }}"
    become: true

  - name: Common | Patching | Copy daily cron
    template:
      src: patchmonkey-daily.cron.j2
      dest: /etc/cron.daily/patchmonkey-daily.cron
      owner: root
      group: root
      mode: 0775
    become: true

  - name: Common | Users | Systemd User Dir
    file:
      path: "{{ homedir }}/.config/systemd/user"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    when: ansible_service_mgr == "systemd"

  - name: Common | Users | copy bashrc
    copy:
      src: bashrc
      dest: "{{ homedir }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Common | Users | copy bash profile
    copy:
      src: bash_profile
      dest: "{{ homedir }}/.bash_profile"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Common | Users | copy toprc
    copy:
      src: toprc
      dest: "{{ homedir }}/.toprc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Common | Users | copy git config
    template:
      src: git_config.j2
      dest: "{{ homedir }}/.gitconfig"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644

  - name: Common | Users | setup git signing
    git_config:
      name: commit.gpgsign
      repo: "{{ homedir }}/.ansible"
      scope: local
      value: true

  - name: Common | Access | Authorized Keys
    authorized_key:
      user: "{{ user }}"
      key: "{{ auth_key_url }}"

  - name: Bin Dir | Binfiles
    copy:
      src: bin/
      dest: "{{ homedir }}/bin/"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
