---
# - name: Administrative | Ansible playbooks
#   git:
#     repo: git@github.com:clcollins/ansible.git
#     dest: /home/chris/.ansible
#     key_file: /home/chris/.ssh/id_ed25519
#     clone: yes
#     update: yes

  - name: Administrative | Copy ansible.cfg
    copy:
      src: ansible.cfg
      dest: /etc/ansible/ansible.cfg
      owner: root
      group: root
      mode: 0644

  - name: Administrative | Add Ansible logdir
    file:
      path: /var/log/ansible
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Administrative | Add Ansible hourly logfile
    file:
      path: /var/log/ansible/ansible-hourly.log
      state: touch
      mode: 0755
      owner: root
      group: root

  - name: Administrative | Copy Ansible hourly cron
    copy:
      src: ansible-hourly.cron
      dest: /etc/cron.hourly/ansible-hourly.cron
      owner: root
      group: root
      mode: 0775

  - name: Access | Authorized Keys
    authorized_key:
      user: chris
      key: https://github.com/clcollins.keys

  - name: Users | copy bashrc 
    copy:
      src: bashrc-chris
      dest: /home/chris/.bashrc
    become: chris
      
  - name: Users | copy bash profile 
    copy:
      src: bash_profile-chris
      dest: /home/chris/.bash_profile
    become: chris

  - name: Users | copy toprc 
    copy:
      src: toprc-chris
      dest: /home/chris/.toprc
    become: chris
      
  - name: Git Config | user name
    git_config:
      name: user.name
      scope: global
      value: Christopher Collins

  - name: Git Config | user email
    git_config:
      name: user.email
      scope: global
      value: collins.christopher@gmail.com

  - name: Git Config | editor
    git_config:
      name: core.editor
      scope: global
      value: vim

  - name: Bin Dir | Binfiles
    copy:
      src: bin/
      dest: /home/chris/bin/
      mode: 0755
    become: chris

  - name: Vim Config | Copy .vimrc 
    copy:
      src: vimrc-chris
      dest: /home/chris/.vimrc
    become: chris

  - name: Vim Config | Pathogen prep
    file:
      path: /home/chris/.vim/autoload
      state: directory
      mode: 0755

  - name: Vim Config | Pathogen prep
    file:
      path: /home/chris/.vim/bundle
      state: directory
      mode: 0755

  - name: Vim Config | Pathogen
    get_url:
      url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest: /home/chris/.vim/autoload/pathogen.vim
      checksum: sha256:b05ef1d37eaf81a93ee07f52e443e0b53ea24eaef752e918763d2eff7758d70e

  - include: vim_plugins.yml
