---
  - name: Gather OS info
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
      - default.yml
    tags:
      - always

  - name: Print OS info
    debug:
      msg: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    tags:
      - always

  - name: Set host nodename
    hostname:
      name: "{{ ansible_nodename }}"
    become: true
    tags:
      - hostConfig

  - name: Create group "{{ user }}"
    group:
      name: "{{ user }}"
      state: present
    become: true
    tags:
      - userConfig

  - name: Add user "{{ user }}"
    user:
      name: "{{ user }}"
      group: "{{ user }}"
      groups: "{{ item }}"
      shell: /bin/bash
      append: yes
    become: true
    with_items:
      - "{{ user }}"
      - "{{ distro_sudoers_group }}"
    tags:
      - userConfig

  - name: Create systemd userdir
    file:
      path: "{{ homedir }}/.config/systemd/user"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    when: ansible_service_mgr == "systemd"
    tags:
      - userConfig

  - name: Create .bashrc
    copy:
      src: bashrc
      dest: "{{ homedir }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
    tags:
      - userConfig
      - dotFiles

  - name: Create .bash_profile
    copy:
      src: bash_profile
      dest: "{{ homedir }}/.bash_profile"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
    tags:
      - userConfig
      - dotFiles

  - name: Create .toprc
    copy:
      src: toprc
      dest: "{{ homedir }}/.toprc"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
    tags:
      - userConfig
      - dotFiles

  - name: Ensure git installed
    package:
      name: git
      state: present
    become: true
    tags:
      - userConfig
      - packages

  - name: Create .giconfig
    template:
      src: git_config.j2
      dest: "{{ homedir }}/.gitconfig"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
    tags:
      - userConfig
      - dotFiles

  - name: Enable git commit signing
    git_config:
      name: commit.gpgsign
      repo: "{{ homedir }}/.ansible"
      scope: global
      value: true
    tags:
      - userConfig
      - gitConfig

  - name: Copy authorized keys
    authorized_key:
      user: "{{ user }}"
      key: "{{ auth_key_url }}"
    tags:
      - userConfig
      - ssh

  - name: Install user binfiles
    copy:
      src: bin/
      dest: "{{ homedir }}/.local/bin/"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    tags:
      - userConfig
      - binFiles
