---
# file: host_vars/marvin.yml

config_user_enable: True
config_gnome_enable: True

config_networking_hostname: marvin
config_vpn_enable: True

flatpak_repositories_enable: True
flatpak_packages_enable: True
