---
# file: host_vars/trillian.yml

config_user_enable: True
config_users_overrides:
  chris:
    home: /var/home/chris

config_hostname: trillian
config_vpn_enable: True

config_gnome_enable: True

flatpak_repositories_enable: True
flatpak_packages_enable: True
