---
# file: host_vars/zaphod.yml

config_networking_hostname: zaphod
config_gnome_enable: True

flatpak_repositories_enable: True
flatpak_packages_enable: True

flatpak_packages_extra:
  - name: org.gimp.Gimp
    remote: flathub
  - name: or.videolan.VLC
    remote: flathub
