# file: base/tasks/main.yml

- name: Copy authorized_keys
  authorized_key:
    user: "{{ ansible_env['USER'] }}"
    state: present
    key: https://github.com/clcollins.keys
  tags:
    - userConfig
    - ssh

