# file: base/tasks/main.yml

- name: System Info
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}"

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  tags:
    - administration
  when: hostname is defined
  become: True

- name: Ensure groups exist
  group:
    name: "{{ item }}"
    state: present
  tags:
    - groupConfig
  with_items: "{{ user_groups }}"
  become: True

- name: Ensure users exist
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
  tags:
    - userConfig
  with_items: "{{ users }}"
  become: True

- name: Copy authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: https://github.com/clcollins.keys
    manage_dir: yes
  tags:
    - userConfig
    - ssh
  with_items: "{{ users }}"
  become: True

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
  become: True

- name: Add own hostname for localhost
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostname }}$'
    line: "{{ item }} {{ hostname }}"
    state: present
  with_items:
    - 127.0.1.1
  become: True

- name: Remove default RPi hostname from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.1.1.*raspberrypi$'
    state: absent
  become: True
