---
  - include: aws.yml
  - include: terraform.yml
  - include: openshift.yml

  - name: Packages | dwarffortress
    dnf:
      name: dwarffortress
      state: present

  - name: Packages | dwarftherapist
    dnf:
      name: dwarftherapist
      state: present

  - name: Packages | qt5-qtbase-devel | qmake, for compiling DT
    dnf:
      name: qt5-qtbase-devel
      state: present

  - name: Packages | qt5-qtdeclarative-devel | qmake, for compiling DT
    dnf:
      name: qt5-qtdeclarative-devel
      state: present

  - name: Packages | texlive-latex-bin | for pdflatex, for compiling DT
    dnf:
      name: texlive-latex-bin
      state: present

  - name: Packages | texlive-latex | for pdflatex, for compiling DT
    dnf:
      name: texlive-latex
      state: present

  - name: Packages | wine | for WoW
    dnf:
      name: wine
      state: present

  - name: Packages | wine-devel | for WoW
    dnf:
      name: wine-devel
      state: present

  - name: Config Files | DF init.txt
    copy:
      src: dwarffortress_init.txt
      dest: "{{ homedir }}/.dwarffortress/data/init/init.txt"
    become: true
    become_user: "{{ user }}"

  # From http://www.bay12forums.com/smf/index.php?topic=158914.0
  - name: Config Files | DF tile
    copy:
      src: hack_square_64x64.png
      dest: "{{ homedir }}/.dwarffortress/data/art/hack_square_64x64.png"
    become: true
    become_user: "{{ user }}"

