---
  - name: Administrative | hostname
    hostname:
      name:  krang.oit.duke.edu

  - name: Package Repos | Fedora DwarfFortress | for FUN!
    yum_repository:
      name: dwarffortress
      description: Dwarf Fortress for Fedora $releasever
      baseurl: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/$releasever/$basearch/
      gpgkey: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/df_gpg_key
      enabled: yes

  - name: Package Repos | RPMFusion | for mplayer, others
    yum_repository:
      name: rpmfusion-free
      description: RPM Fusion for Fedora $releasever - Free
      baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-25
      #gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: yes

  - name: Package Repos | RPMFusion | for mplayer, others
    yum_repository:
      name: rpmfusion-free-updates
      description: RPM Fusion for Fedora $releasever - Free - Updates
      baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
      mirrorlist: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
      gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-25
      #gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      gpgcheck: yes
      enabled: yes

  - name: Packages | patch all
    dnf:
      name: "*"
      state: latest

  - name: Packages | dwarffortress
    dnf:
      name: dwarffortress
      state: latest

  - name: Packages | dwarftherapist
    dnf:
      name: dwarftherapist
      state: latest

  - name: Packages | ansible
    dnf:
      name: ansible
      state: latest

  - name: Packages | docker
    dnf:
      name: docker
      state: latest

  - name: Packages | docker-compose
    dnf:
      name: docker-compose
      state: latest

  - name: Packages | wine | for WoW
    dnf:
      name: wine
      state: latest

  - name: Packages | wine-devel | for WoW
    dnf:
      name: wine-devel
      state: latest

  - name: Packages | the_silver_searcher | for fast search
    dnf:
      name: the_silver_searcher
      state: latest

  - name: Packages | redhat-rpm-config | for lolcommits
    dnf:
      name: redhat-rpm-config
      state: latest

  - name: Packages | mplayer | for lolcommits
    dnf:
      name: mplayer
      state: latest

  - name: Packages | ImageMagick | for lolcommits
    dnf:
      name: ImageMagick
      state: latest

  - name: Packages | ImageMagick-devel | for lolcommits
    dnf:
      name: ImageMagick-devel
      state: latest

  - name: Packages | ruby-devel | for ruby
    dnf:
      name: ruby-devel
      state: latest

  - name: Packages | rubygems | for ruby
    dnf:
      name: rubygems
      state: latest

  - name: Packages | openssl-devel | for ruby
    dnf:
      name: openssl-devel
      state: latest

  - name: Packages | readline-devel | for ruby
    dnf:
      name: readline-devel
      state: latest

  - name: Packages | rubypick | for ruby
    dnf:
      name: rubypick
      state: latest

  - name: Gems | rails | for ruby
    gem:
      name: rails
      state: latest
    become: chris

  - name: Gems | lolcommits | for fun
    gem:
      name: lolcommits
      state: latest
    become: chris

  - name: Unpackaged Software | rbenv | for ruby
    git:
      repo: git://github.com/sstephenson/rbenv.git
      dest: /home/chris/.rbenv
      update: no
    become: chris

  - name: Unpackaged Software | ruby-build | for ruby
    git:
      repo: git://github.com/sstephenson/ruby-build.git
      dest: /home/chris/.rbenv/plugins/ruby-build
      update: no
    become: chris

  - name: Config Files | DF init.txt
    copy:
      src: dwarffortress_init.txt
      dest: /home/chris/.dwarffortress/data/init/init.txt
    become: chris

  - name: Config Files | Docker Storage Setup
    copy:
      src: docker-storage-setup
      dest: /etc/sysconfig/docker-storage-setup
    notify: reload docker

  - name: Config Files | Docker Network Setup
    copy:
      src: docker-network
      dest: /etc/sysconfig/docker-storage-setup
    notify: reload docker

  - name: Config Files | .docker Directory
    file:
      path: /home/chris/.docker
      state: directory
      mode: 0755
      owner: chris
      group: chris
  
