---
  - name: Administrative | hostname
    hostname:
      name:  krang.oit.duke.edu

  - name: Package Repos | Fedora DwarfFortress | for FUN!
    yum_repository:
      name: dwarffortress
      description: Dwarf Fortress for Fedora $releasever
      baseurl: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/$releasever/$basearch/
      gpgkey: https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/df_gpg_key
      enabled: yes

  - name: Packages | dwarffortress
    dnf:
      name: dwarffortress
      state: latest

  - name: Packages | dwarftherapist
    dnf:
      name: dwarftherapist
      state: latest

  - name: Packages | ansible
    dnf:
      name: ansible
      state: latest

  - name: Packages | docker
    dnf:
      name: docker
      state: latest

  - name: Packages | docker-compose
    dnf:
      name: docker-compose
      state: latest

  - name: Packages | gcc-c++ | for various
    dnf:
      name: gcc-c++
      state: latest

  - name: Packages | redhat-rpm-config | for lolcommits
    dnf:
      name: redhat-rpm-config
      state: latest

  - name: Packages | kmplayer | for lolcommits
    dnf:
      name: kmplayer
      state: latest

  - name: Packages | ImageMagick | for lolcommits
    dnf:
      name: ImageMagick
      state: latest

  - name: Packages | ImageMagick-devel | for lolcommits
    dnf:
      name: ImageMagick-devel
      state: latest

  - name: Packages | ruby-devel | for ruby
    dnf:
      name: ruby-devel
      state: latest

  - name: Packages | rubygems | for ruby
    dnf:
      name: rubygems
      state: latest

  - name: Packages | openssl-devel | for ruby
    dnf:
      name: openssl-devel
      state: latest

  - name: Packages | readline-devel | for ruby
    dnf:
      name: readline-devel
      state: latest

  - name: Packages | rubypick | for ruby
    dnf:
      name: rubypick
      state: latest

  - name: Gems | rails | for ruby
    gem:
      name: rails
      state: latest
    become: chris

  - name: Gems | lolcommits | for fun
    gem:
      name: lolcommits
      state: latest
    become: chris

  - name: Users | copy bashrc 
    copy:
      src: bashrc-chris
      dest: /home/chris/.bashrc
    become: chris
      
  - name: Users | copy bash profile 
    copy:
      src: bash_profile-chris
      dest: /home/chris/.bash_profile
    become: chris
      
  - name: Unpackaged Software | rbenv | for ruby
    git:
      repo: git://github.com/sstephenson/rbenv.git
      dest: /home/chris/.rbenv
      update: no
    become: chris

  - name: Unpackaged Software | ruby-build | for ruby
    git:
      repo: git://github.com/sstephenson/ruby-build.git
      dest: /home/chris/.rbenv/plugins/ruby-build
      update: no
    become: chris

  - name: Config Files | DF init.txt
    copy:
      src: dwarffortress_init.txt
      dest: /home/chris/.dwarffortress/data/init/init.txt
    become: chris
