---
  - name: Administrative | hostname
    hostname:
      name:  krang.oit.duke.edu

  - name: Packages | dwarffortress
    dnf:
      name: dwarffortress
      state: latest

  - name: Packages | dwarftherapist
    dnf:
      name: dwarftherapist
      state: latest

  - name: Packages | qt5-qtbase-devel | qmake, for compiling DT
    dnf:
      name: qt5-qtbase-devel
      state: latest

  - name: Packages | qt5-qtdeclarative-devel | qmake, for compiling DT
    dnf:
      name: qt5-qtdeclarative-devel
      state: latest

  - name: Packages | texlive-latex-bin | for pdflatex, for compiling DT
    dnf:
      name: texlive-latex-bin
      state: latest

  - name: Packages | texlive-latex | for pdflatex, for compiling DT
    dnf:
      name: texlive-latex
      state: latest

  - name: Packages | wine | for WoW
    dnf:
      name: wine
      state: latest

  - name: Packages | wine-devel | for WoW
    dnf:
      name: wine-devel
      state: latest

  - name: Packages | mplayer | for lolcommits
    dnf:
      name: mplayer
      state: latest

  - name: Packages | ImageMagick | for lolcommits
    dnf:
      name: ImageMagick
      state: latest

  - name: Packages | ImageMagick-devel | for lolcommits
    dnf:
      name: ImageMagick-devel
      state: latest

  - name: Gems | lolcommits | for fun
    gem:
      name: lolcommits
      state: latest
    become: chris

  - name: Config Files | DF init.txt
    copy:
      src: dwarffortress_init.txt
      dest: /home/chris/.dwarffortress/data/init/init.txt
    become: chris

  # From http://www.bay12forums.com/smf/index.php?topic=158914.0
  - name: Config Files | DF tile
    copy:
      src: hack_square_64x64.png
      dest: /home/chris/.dwarffortress/data/art/hack_square_64x64.png
    become: chris

