---
- name: install common packages 
  package:
    name: 
      - "{{ general_packages[ansible_distribution] }}"
    state: present
  become: true
  tags:
    - packages

- name: load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ kernel_modules }}"
  become: true
  tags:
    - kernel_modules
    - cri-o

- name: enable persistent kernel modules
  copy:
    dest: "/etc/modules-load.d/{{ item }}"
    content: |
      # Load {{ item }} at boot time
      {{ item }}
  with_items:
    - "{{ kernel_modules }}"
  become: true
  tags:
    - kernel_modules
    - cri-o

- name: CRI-O sysctl entries
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ crio_sysctl_configs }}"
  become: true
  tags:
    - sysctl_entires
    - cri-o

- name: add repo keys (apt)
  apt_key:
    url: "{{ item.key }}"
    state: present
  with_items:
    - "{{ crio_repos[ansible_distribution] }}"
    - "{{ kube_repos[ansible_distribution] }}"
  become: true
  when: 
    - ansible_facts['distribution'] == "Ubuntu"
  tags:
    - apt
    - repos
    - cri-o
    - kubernetes

- name: add repos (apt)
  apt_repository:
    repo: "{{ item.name }}"
    state: present
  with_items:
    - "{{ crio_repos[ansible_distribution] }}"
    - "{{ kube_repos[ansible_distribution] }}"
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  become: true
  tags:
    - apt
    - repos 
    - cri-o
    - kubernetes


- name: add repos (dnf)
  copy:
    dest: "{{ item.destination }}"
    content: "{{ item.content }}"
  when:
    - ansible_facts['distribution'] == "Fedora"
  with_items:
    - "{{ crio_repos[ansible_distribution] }}"
    - "{{ kube_repos[ansible_distribution] }}"
  become: true
  tags:
    - dnf
    - repos
    - cri-o

- name: add packages (Ubuntu)
  package:
    name: 
      - "{{ crio_packages[ansible_distribution] }}"
      - "{{ kube_packages }}"
    state: present
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  tags:
    - packages
    - cri-o
    - kubernetes

# Required to utilize the --disableexcludes=kubernetes flag
# This effectively "holds" kubernetes packages during other 
# DNF updates
- name: add cri-o packages (Fedora)
  dnf:
    name: "{{ crio_packages[ansible_distribution] }}"
    state: present
  become: true
  when:
    - ansible_facts['distribution'] == "Fedora"
  tags:
    - packages
    - cri-o
    - kubernetes

- name: add kubernetes packages (Fedora)
  dnf:
    name: "{{ kube_packages }}"
    state: present
    disable_excludes: kubernetes
  become: true
  when:
    - ansible_facts['distribution'] == "Fedora"
  tags:
    - packages
    - cri-o
    - kubernetes

- name: hold Kube and Crio packages (dpkg)
  dpkg_selections:
    name:
      - "{{ crio_packages }}"
      - "{{ kube_packages }}"
    selection: hold
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  tags:
    - dpkg
    - packages
    - cri-o
    - kubernetes

- name: enable service cri-o and ensure it is not masked
  systemd:
    name: "{{ crio_service[ansible_distribution] }}"
    state: started
    enabled: yes
    masked: no
  become: true
  tags:
    - systemd
    - cri-o

- name: ensure kubelet.service.d exists
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
  become: true
  tags:
    - kubernetes
    - systemd

- name: ensure systemd cgroups driver
  copy:
    src: 10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: true
  tags:
    - kubernetes
    - systemd
  register: kubelet_service

- name: reload and restart kubelet
  systemd:
    name: "{{ kubelet_service[ansible_distribution] }}"
    state: restarted
    enabled: yes
    masked: no
  become: true
  tags:
    - systemd
    - cri-o
  when: kubelet_service.changed|bool

- name: add control plane hostname to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{ control_plane_dns_name }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.kubePrimary }}"
  become: True
  tags:
    - etc_hosts
 
