---
# file: roles/package-repositories/vars/main.yml

yum_repositories:
    rpmfusion:
      - name: rpmfusion-free
        description: RPM Fusion for Fedora $releasever - Free
        #baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
        enabled: 1
        metadata_expire: 14d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-debuginfo
        description: RPM Fusion for Fedora $releasever - Free - Debug
        #baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-debug-$releasever&arch=$basearch
        enabled: 0
        metadata_expire: 7d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-source
        description: RPM Fusion for Fedora $releasever - Free - Source
        #baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/source/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-source-$releasever&arch=$basearch
        enabled: 0
        metadata_expire: 7d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates
        description: RPM Fusion for Fedora $releasever - Free - Updates
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
        enabled: 1
        enabled_metadata: 1
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates-debuginfo
        description: RPM Fusion for Fedora $releasever - Free - Updates Debug
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-debug-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates-source
        description: RPM Fusion for Fedora $releasever - Free - Updates Source
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-source-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates-testing
        description: RPM Fusion for Fedora $releasever - Free - Test Updates
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-$releasever&arch=$basearch
        enabled: 0
        enabled_metadata: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates-testing-debuginfo
        description: RPM Fusion for Fedora $releasever - Free - Test Updates Debug
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-debug-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-free-updates-testing-source
        description: RPM Fusion for Fedora $releasever - Free - Test Updates Source
        #baseurl: http://download1.rpmfusion.org/free/fedora/updates/testing/$releasever/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-testing-source-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
      - name: rpmfusion-nonfree
        description: RPM Fusion for Fedora $releasever - Nonfree
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
        enabled: 1
        enabled_metadata: 1
        metadata_expire: 14d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-debuginfo
        description: RPM Fusion for Fedora $releasever - Nonfree - Debug
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-debug-$releasever&arch=$basearch
        enabled: 0
        metadata_expire: 7d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-source
        description: RPM Fusion for Fedora $releasever - Nonfree - Source
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/source/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-source-$releasever&arch=$basearch
        enabled: 0
        metadata_expire: 7d
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates
        description: RPM Fusion for Fedora $releasever - Nonfree - Updates
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
        enabled: 1
        enabled_metadata: 1
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates-debuginfo
        description: RPM Fusion for Fedora $releasever - Nonfree - Updates Debug
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-debug-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates-source
        description: RPM Fusion for Fedora $releasever - Nonfree - Updates Source
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-source-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates-testing
        description: RPM Fusion for Fedora $releasever - Nonfree - Test Updates
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-$releasever&arch=$basearch
        enabled: 0
        enabled_metadata: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates-testing-debuginfo
        description: RPM Fusion for Fedora $releasever - Nonfree - Test Updates Debug
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/$basearch/debug/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-debug-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
      - name: rpmfusion-nonfree-updates-testing-source
        description: RPM Fusion for Fedora $releasever - Nonfree - Test Updates Source
        #baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/testing/$releasever/SRPMS/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-testing-source-$releasever&arch=$basearch
        enabled: 0
        type: rpm-md
        gpgcheck: 1
        repo_gpgcheck: 0
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
