---
# file: roles/minishift/tasks/main.yml

- name: install Minishift kvm dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ minishift_kvm_package_dependencies }}"
    - "{{ minishift_kvm_package_helpers }}"
  become: true
  tags:
    - minishift

- name: add user to libvirt group
  user:
    name: "{{ ansible_env['USER'] }}"
    groups: libvirt
    append: yes
  become: true
  tags:
    - minishift

- name: download KVM driver binary
  get_url:
    url: "{{ minishift_kvm_driver_url }}"
    dest: "{{ minishift_kvm_driver_dest }}"
    mode: '0755'
  become: true
  tags:
    - minishift

- name: download Minishift release
  get_url:
    url: "https://github.com/minishift/minishift/releases/download/v{{ minishift_release_version }}/minishift-{{ minishift_release_version }}-linux-amd64.tgz"
    dest: "{{ minishift_tarball }}"
#    checksum: sha256:https://github.com/minishift/minishift/releases/download/v{{ minishift_release_version }}/minishift-{{ minishift_release_version }}-linux-amd64.tgz.sha256
  tags:
    - minishift

- name: extract Minishift
  unarchive:
    src: "{{ minishift_tarball }}"
    dest: "{{ homedir }}/.local/bin"
    mode: '0755'
    extra_opts:
      - "minishift-{{ minishift_release_version }}-linux-amd64/minishift"
      - --strip-components=1
  tags:
    - minishift
