---
  - name: Remove ssh from default firewalld zone
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: disabled
    with_items: "{{ public_zones }}"
    become: true
    notify: reload firewalld

  - name: Add ssh to internal zones
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: enabled
    with_items: "{{ private_zones }}"
    become: true
    notify: reload firewalld

  - name: Check for host ed25519 key 
    stat:
      path: /etc/ssh/ssh_host_ed25519_key.pub
    register: ssh_host_ed25519_key

  - name: Generate ed25519 via systemd target
    systemd:
      name: sshd-keygen.target
      state: restarted
    become: true
    when: ssh_host_ed25519_key.stat.exists == False

  - name: Copy sshd_config
    template:
      src: sshd_config.j2
      dest: /etc/ssh/ssh_config.d/80-sshd_config
      backup: yes
      owner: root
      group: root
      mode: 0644
      validate: '/usr/sbin/sshd -T -f %s'
    become: true
    notify:
      - reload sshd
    tags:
      - sshd
      - configs

  - name: Ensure sshd is running
    systemd:
      name: sshd
      state: started
    become: true
