---

  - name: sshd | Install sshd
    package:
      name: "{{ sshd }}"
      state: present
    become: true
    tags:
      - sshd
      - packages

  - name: sshd | remove from default
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: disabled
    with_items: "{{ public_zones }}"
    become: true
    notify: reload firewalld

  - name: sshd | add to internal
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: enabled
    with_items: "{{ private_zones }}"
    become: true
    notify: reload firewalld

  - name: sshd | check-keygen
    stat:
      path: /etc/ssh/ssh_host_ed25519_key.pub
    register: ssh_host_ed25519_key

  - name: sshd | sshd-keygen (systemd target)
    systemd:
      name: sshd-keygen.target
      state: restarted
    become: true
    when: ssh_host_ed25519_key.stat.exists == False

  - name: sshd | sshd_config
    template:
      src: sshd_config.j2
      dest: /etc/ssh/ssh_config.d/80-sshd_config
      backup: yes
      owner: root
      group: root
      mode: 0644
      validate: '/usr/sbin/sshd -T -f %s'
    become: true
    notify:
      - reload sshd
    tags:
      - sshd
      - configs

  - name: sshd | sshd service on
    systemd:
      name: sshd
      state: started
    become: true

