---
  - name: Debug
    debug:
      msg: "{{ ansible_distribution }}"
    tags:
      - debug

  - name: Fix bug with cockpit and firewalld in Fedora (bugzilla 1171114)
    lineinfile:
      path: /usr/lib/firewalld/zones/FedoraServer.xml
      line: '  <service name="cockpit"/>'
      state: absent
    when:
      - ansible_distribution_major_version|int < 29
      - ansible_distribution == "Fedora"
    tags:
      - bugfix

  - name: Remove ssh from default firewalld zone
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: disabled
    with_items: "{{ public_zones }}"
    become: true
    notify: reload firewalld
    tags:
      - sshd
      - firewalld

  - name: Add ssh to internal zones
    firewalld:
      zone: "{{ item }}"
      service: ssh
      permanent: true
      state: enabled
    with_items: "{{ private_zones }}"
    become: true
    notify: reload firewalld
    tags:
      - sshd
      - firewalld

  - name: Check for host ed25519 key
    stat:
      path: /etc/ssh/ssh_host_ed25519_key.pub
    register: ssh_host_ed25519_key
    tags:
      - sshd

  - name: Generate ed25519 via systemd target
    systemd:
      name: sshd-keygen.target
      state: restarted
    become: true
    when: ssh_host_ed25519_key.stat.exists == False
    tags:
      - sshd

  - name: Copy sshd_config
    template:
      src: sshd_config.j2
      dest: /etc/ssh/ssh_config.d/80-sshd_config
      backup: yes
      owner: root
      group: root
      mode: 0644
      validate: '/usr/sbin/sshd -T -f %s'
    become: true
    notify:
      - reload sshd
    tags:
      - sshd

  - name: Ensure sshd is running
    systemd:
      name: sshd
      state: started
    become: true
    tags:
      - sshd
