---
# file: roles/sshd/tasks/main.yml
  - name: gather os specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - defaults.yml
    tags:
      - sshd
      - vars

  - name: Ensure SSH daemon is installed
    package:
      name: "{{ sshd_package_name }}"
      state: present
    become: true
    tags:
      - sshd
    when:
      - ansible_facts['pkg_mgr'] != "atomic_container"

  - name: Copy sshd_config
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
    become: true
    tags:
      - sshd

  - name:  Enable sshd service
    systemd:
      name: "{{ sshd_service_name }}"
      scope: system
      enabled: yes
      state: started
    become: true
    tags:
      - sshd
  
